service: github
frameworkVersion: '3'

dataplattform:
  dependencies:
    - ../../infrastructure/deploymentBucket
    - ../../infrastructure/datalake
    - ../../infrastructure/events
    - ../../infrastructure/monitoring
    - ../../infrastructure/glue
    - ../../infrastructure/ingestApiGateway
  glue:
    tableName: github
    accessLevel: 2
  hooks:
    - name: 'Invoke ingestor'
      trigger: postDeploy
      type: invoke
      value: pollerIngest

custom:
  editable:
    scheduleRate: rate(7 days)
    timeout: 15
    srcDir: lib/github
    webhookIngestHandlerFile: github_webhook_ingest_handler
    pollerIngestHandlerFile: github_poller_ingest_handler
    processHandlerFile: github_process_handler
    databaseName: level_2
    description: Endpoint for github webhooks and scheduled events
    accessLevel: level-2
    dataFolder: github/repos
  project: dataplattform
  service: ${sls:stage}-${self:service}
  accessPath: data/${self:custom.editable.accessLevel}/${self:custom.editable.dataFolder}/
  sqsQueueName: ${sls:stage}-${self:service}-sqs.fifo
  sqsQueueDLName: ${sls:stage}-${self:service}-sqs-dl.fifo
  pythonRequirements:
    dockerImage: public.ecr.aws/sam/build-python3.9
    dockerizePip: non-linux
    noDeploy:
      - boto3
      - botocore

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${sls:stage}-${self:service}
  deploymentBucket:
    name: ${sls:stage}-${file(../../infrastructure/deploymentBucket/config.yml):bucketName, file(../../infrastructure/deploymentBucket/serverless.yml):defaultBucketName}
  runtime: python3.9
  memorySize: 1024
  timeout: ${self:custom.editable.timeout}

  # imports api gateway resources exported by ingestApiGateway service
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${sls:stage}-ingestApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${sls:stage}-ingestApiGateway-rootResourceId

  tags:
    project: ${self:custom.project}
    layer: ingestion
    ingestion: webHooks
  stackTags:
    project: ${self:custom.project}
    layer: ingestion
    ingestion: webHooks
  tracing:
    lambda: true

package:
  individually: true
  exclude:
    - "./**"

functions:
  pollerIngest:
    handler: ${self:custom.editable.srcDir}/${self:custom.editable.pollerIngestHandlerFile}.handler
    name: ${sls:stage}-${self:service}-poller-ingest
    description: ${self:custom.editable.description}
    role: !GetAtt PollerIngestLambdaRole.Arn
    package:
      include:
        - '${self:custom.editable.srcDir}/*.py'
    environment:
      STAGE: ${sls:stage}
      SERVICE: ${self:service}
      DATALAKE: !ImportValue ${sls:stage}-datalakeName
      ACCESS_PATH: ${self:custom.accessPath}
      DEFAULT_DATABASE: ${self:custom.editable.databaseName}
      SQS_QUEUE_NAME: ${self:custom.sqsQueueName}
      SQS_MESSAGE_GROUP_ID: ${self:custom.sqsQueueName}-group1
    events:
      - schedule:
          name: ${sls:stage}-${self:service}-timer
          description: ${self:custom.editable.description}
          rate: ${self:custom.editable.scheduleRate}
          enabled: true
  webhookIngest:
    handler: ${self:custom.editable.srcDir}/${self:custom.editable.webhookIngestHandlerFile}.handler
    name: ${sls:stage}-${self:service}-webhook-ingest
    description: ${self:custom.editable.description}
    role: !GetAtt WebhookIngestLambdaRole.Arn
    package:
      include:
        - '${self:custom.editable.srcDir}/*.py'
    environment:
      STAGE: ${sls:stage}
      SERVICE: ${self:service}
      DATALAKE: !ImportValue ${sls:stage}-datalakeName
      ACCESS_PATH: ${self:custom.accessPath}
      DEFAULT_DATABASE: ${self:custom.editable.databaseName}
      SQS_QUEUE_NAME: ${self:custom.sqsQueueName}
      SQS_MESSAGE_GROUP_ID: ${self:custom.sqsQueueName}-group1
    events:
      - http:
          path: github-ingest/
          method: post
          private: false # if true API key is needed
  process:
    handler: ${self:custom.editable.srcDir}/${self:custom.editable.processHandlerFile}.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EventQueue
              - Arn
          batchSize: 1
    name: ${sls:stage}-${self:service}-process
    description: ${self:custom.editable.description}
    role: !GetAtt ProcessLambdaRole.Arn
    package:
      include:
        - '${self:custom.editable.srcDir}/*.py'
    environment:
      STAGE: ${sls:stage}
      SERVICE: ${self:service}
      DATALAKE: !ImportValue ${sls:stage}-datalakeName
      ACCESS_PATH: ${self:custom.accessPath}
      DEFAULT_DATABASE: ${self:custom.editable.databaseName}
      DATA_UPDATE_TOPIC: !ImportValue ${sls:stage}-data-update-topic-arn
      ACCESS_LEVEL: ${self:custom.editable.accessLevel}

resources:
  Resources:
    PollerIngestLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${sls:stage}-${self:service}-poller-ingest-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
          - !ImportValue ${sls:stage}-lambda-xray-tracing
        Policies:
          - PolicyName: ${sls:stage}-DatalakeIO-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:ListObjects*
                    - s3:GetObject
                    - s3:CopyObject
                    - s3:DeleteObjects
                  Resource:
                    - Fn::Join:
                        - ""
                        - - !ImportValue ${sls:stage}-datalakeArn
                          - /${self:custom.accessPath}*
          - PolicyName: ${sls:stage}-${self:service}-poller-ingest-sqsRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:GetQueueUrl
                    - sqs:SendMessageBatch
                    - sqs:SendMessage
                  Resource: !GetAtt EventQueue.Arn
          - PolicyName: ${sls:stage}-ParameterStore-${self:service}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'ssm:GetParameter*'
                  Resource:
                    !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${sls:stage}/${self:service}/*'
    WebhookIngestLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${sls:stage}-${self:service}-webhook-ingest-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
          - !ImportValue ${sls:stage}-lambda-xray-tracing
        Policies:
          - PolicyName: ${sls:stage}-DatalakeIO-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:ListObjects*
                    - s3:GetObject
                    - s3:CopyObject
                    - s3:DeleteObjects
                  Resource:
                    - Fn::Join:
                        - ""
                        - - !ImportValue ${sls:stage}-datalakeArn
                          - /${self:custom.accessPath}*
          - PolicyName: ${sls:stage}-ParameterStore-${self:service}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'ssm:GetParameter*'
                  Resource:
                    !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${sls:stage}/${self:service}/*'
          - PolicyName: ${sls:stage}-${self:service}-webhook-ingest-sqsRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:GetQueueUrl
                    - sqs:SendMessageBatch
                    - sqs:SendMessage
                  Resource: !GetAtt EventQueue.Arn
    ProcessLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${sls:stage}-${self:service}-${self:custom.editable.processHandlerFile}-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole"
          - !ImportValue ${sls:stage}-process-lambda-topic-access-role
          - !ImportValue ${sls:stage}-lambda-xray-tracing
        Policies:
          - PolicyName: ${sls:stage}-DatalakeIO-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:ListObjects*
                    - s3:GetObject
                    - s3:CopyObject
                    - s3:DeleteObjects
                  Resource:
                    - Fn::Join:
                        - ""
                        - - !ImportValue ${sls:stage}-datalakeArn
                          - /${self:custom.accessPath}*
          - PolicyName: ${sls:stage}-DatalakeBucket-${self:service}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:ListBucket
                    - s3:GetBucketLocation
                  Resource:
                    - Fn::Join:
                        - ""
                        - - !ImportValue ${sls:stage}-datalakeArn
                          - '*'
          - PolicyName: ${sls:stage}-Glue-${self:service}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'glue:GetTable'
                    - 'glue:GetDatabase'
                    - 'glue:GetPartitions'
                  Resource:
                    - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
                    - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${sls:stage}_${self:custom.editable.databaseName}_database'
                    - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${sls:stage}_${self:custom.editable.databaseName}_database/*'
          - PolicyName: ${sls:stage}-Athena-${self:service}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'athena:StartQueryExecution'
                    - 'athena:GetQueryExecution'
                    - 'athena:GetQueryResults'
                  Resource: !Sub 'arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary'
          - PolicyName: ${sls:stage}-glue-${self:service}-role
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - glue:GetCrawler
                    - glue:UpdateCrawler
                  Resource:
                    - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
                    - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${sls:stage}_*'
                    - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${sls:stage}_*'
                    - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:crawler/${sls:stage}_*'
    EventQueue:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: ${self:custom.sqsQueueName}
        ContentBasedDeduplication: true # Assume all message bodies are unique, by design given as an uuid1
        VisibilityTimeout: ${self:custom.editable.timeout}
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt EventQueueDL.Arn
          # The number of times a message is delivered to the source queue before being moved to the dead-letter queue.
          maxReceiveCount: 1
    EventQueueDL: # Messages that fail are put here
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: ${self:custom.sqsQueueDLName}
        ContentBasedDeduplication: true # Assume all message bodies are unique, by design given as an uuid1

plugins:
  - serverless-python-requirements
