service: routes
frameworkVersion: '3'

dataplattform:
  dependencies:
    - ../deploymentBucket

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:service}-${sls:stage}
  deploymentBucket:
    name: ${sls:stage}-${file(../deploymentBucket/config.yml):bucketName, file(../deploymentBucket/serverless.yml):defaultBucketName}
  runtime: nodejs16.x

resources:
  Resources:
    BasicZone:
      Type: AWS::Route53::HostedZone
      Properties:
        Name: ${ssm:/${sls:stage}/routes/domain_name}

  Outputs:
    routesZoneId:
      Value:
        "Ref": BasicZone
      Export:
        Name: ${sls:stage}-routes-zoneid
