service: routes
frameworkVersion: '3'

dataplattform:
  dependencies:
    - ../deploymentBucket

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:service}-${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.stage}-${file(../deploymentBucket/config.yml):bucketName, file(../deploymentBucket/serverless.yml):defaultBucketName}
  runtime: nodejs16.x

resources:
  Resources:
    BasicZone:
      Type: AWS::Route53::HostedZone
      Properties:
        Name: ${ssm:/${self:custom.stage}/routes/domain_name}

  Outputs:
    routesZoneId:
      Value:
        "Ref": BasicZone
      Export:
        Name: ${self:custom.stage}-routes-zoneid
