service: cloudwatch
frameworkVersion: '3'

dataplattform:
  dependencies:
    - ../deploymentBucket
    - ../datalake
    - ../kms
    - ../glue

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:service}-${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.stage}-${file(../deploymentBucket/config.yml):bucketName, file(../deploymentBucket/serverless.yml):defaultBucketName}

resources:
  Resources:
    CrawlerLogGroup:
      Type: AWS::Logs::LogGroup
      DeletionPolicy: Retain
      Properties:
        KmsKeyId:
          Fn::Join:
            - ""
            - - !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/
              - !Sub "${ssm:/${self:custom.stage}/kms/key-id}"
        LogGroupName: /aws-glue/crawlers-role/Level4GlueRole-KMSGlueEncryptionConfigurations
