service: metadata
frameworkVersion: '3'

dataplattform:
  dependencies:
    - ../deploymentBucket
    - ../vpc

custom:
  service: ${sls:stage}-${self:service}
  project: dataplattform


provider:
  stage: dev
  name: aws
  region: eu-central-1
  stackName: ${self:custom.service}
  deploymentBucket:
    name: ${sls:stage}-${file(../deploymentBucket/config.yml):bucketName, file(../deploymentBucket/serverless.yml):defaultBucketName}
  runtime: nodejs16.x


resources:
  Resources:
    PersonalMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}_personal_metadata_table
        AttributeDefinitions:
          - AttributeName: guid
            AttributeType: S
        KeySchema:
          - AttributeName: guid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        SSESpecification:
          SSEEnabled: true
          SSEType: KMS

    PersonalMetadataTableAccess:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Access to ${sls:stage} Personal Metadata Table
        ManagedPolicyName: ${sls:stage}-personal-metadata-table
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Batch*
                - dynamodb:DescribeTable
              Resource: !GetAtt PersonalMetadataTable.Arn
  Outputs:
    PersonalMetadataTableAccessOutput:
      Value:
        Ref: PersonalMetadataTableAccess
      Export:
        Name: ${sls:stage}-personal-metadata-table-access-policy
    PersonalMetadataTableName:
      Value: ${self:resources.Resources.PersonalMetadataTable.Properties.TableName}
      Export:
        Name: ${sls:stage}-personal-metadata-table-name
    PersonalMetadataTableArn:
      Value: !GetAtt PersonalMetadataTable.Arn
      Export:
        Name: ${sls:stage}-personal-metadata-tableArn
