service: deploymentBucket
frameworkVersion: '3'

plugins:
  - serverless-deployment-bucket


defaultBucketName: dataplattform-deploymentbucket

custom:
  service: ${sls:stage}-${self:service}
  deploymentBucket:
    blockPublicAccess: true

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.service}
  runtime: nodejs16.x

  # Lag en fil config.yml med feltet "bucketName" hvor du skriver inn et globalt unikt navn for deploymentbucket
  deploymentBucket:
    name: ${sls:stage}-${file(./config.yml):bucketName, self:defaultBucketName}
    serverSideEncryption: AES256

resources:
  Resources:
    NullResource:
      Type: AWS::CloudFormation::WaitConditionHandle
