service: deploymentBucket

plugins:
  - serverless-deployment-bucket

custom:
  stage: ${opt:stage, self:provider.stage}
  service: ${self:custom.stage}-${self:service}
  deploymentBucket:
    blockPublicAccess: true

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.service}
  deploymentBucket:
    name: ${self:custom.stage}-dataplattform-v2-deploymentbucket
    serverSideEncryption: AES256

# Stack will not deploy unless at least one CF resource is defined.
functions:
  null_function:
    enabled: false
    handler: handler.handler
