
name: Dataplattform - api - fileDistribution

on: 
  push:
    branches:
      - master
      - develop
    paths:
      - 'services/api/fileStorageDistribution/**'
      - '.config/.flake8'
      - '.config/.yamllint'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'services/api/fileStorageDistribution/**'
      - '.config/.flake8'
      - '.config/.yamllint'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config=./.config/.flake8 ./services/api/fileStorageDistribution
    - name: Lint with yamllint
      run: |
        pip install yamllint
        yamllint -c ./.config/.yamllint ./services/api/fileStorageDistribution
