
name: Dataplattform - api - dataApi

on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'services/api/dataApi/**'
      - 'packages/api/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config=./.config/.flake8 ./services/api/dataApi
    - name: Lint with yamllint
      run: |
        pip install yamllint
        yamllint -c ./.config/.yamllint ./services/api/dataApi
  
  test:
    runs-on: ubuntu-latest
    container:
      image: lambci/lambda:build-python3.7

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: './services/api/dataApi'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install -r functions/requirements.txt
    - name: Test with pytest
      working-directory: './services/api/dataApi'
      run: |
        pip install pytest
        pytest 