name: Deploy infrastructure - vpc

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
    paths:
      - 'services/infrastructure/vpc/**'
      - '.config/.serverless'
      - '.github/workflows/deploy-infrastructure-vpc.yml'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/infrastructure/vpc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Serverless Framework
        run: npm install -g $(awk -F ":" '/SERVERLESS_VERSION/ {print $2}' ../../../.config/.serverless_vpc)

      - name: Install dependencies
        run: npm install

      - name: Run serverless deploy prod
        if: ${{ github.base_ref == 'master' || github.ref == 'refs/heads/master' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          echo "Deploying to production" && sls deploy --stage prod


      - name: Run serverless deploy dev
        if: ${{ github.base_ref != 'master' && github.base_ref != 'refs/heads/master' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          echo "Deploying to development" && sls deploy --stage dev
