name: Dataplattform - infrastructure - monitoring

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'services/infrastructure/monitoring/**'
      - '.config/.yamllint'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Lint with yamllint
        run: |
          pip install yamllint
          yamllint -c ./.config/.yamllint ./services/infrastructure/monitoring
