
name: Dataplattform - ingestion - googleEvent

on: 
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    paths:
      - 'services/ingestion/googleEvent/**'
      - 'packages/common/**'
      - '.config/.flake8'
      - '.config/.yamllint'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'services/ingestion/googleEvent/**'
      - 'packages/common/**'
      - '.config/.flake8'
      - '.config/.yamllint'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config=./.config/.flake8 ./services/ingestion/googleEvent
    - name: Lint with yamllint
      run: |
        pip install yamllint
        yamllint -c ./.config/.yamllint ./services/ingestion/googleEvent

  test:
    runs-on: ubuntu-latest
    container:
      image: lambci/lambda:build-python3.7

    steps:
    - uses: actions/checkout@v2
    - name: Test with tox/pytest
      working-directory: './services/ingestion/googleEvent'
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        tox