
name: Dataplattform - ingestion - dora

on: 
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    paths:
      - 'services/ingestion/dora/**'
      - 'packages/common/**'
      - '.config/.flake8'
      - '.config/.yamllint'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'services/ingestion/dora/**'
      - 'packages/common/**'
      - '.config/.flake8'
      - '.config/.yamllint'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install yamllint
    - name: Lint with flake8 dora ignestion
      run: |
        flake8 --config=./.config/.flake8 ./services/ingestion/dora
    - name: Lint with yamllint dora ignestion
      run: |
        yamllint -c ./.config/.yamllint ./services/ingestion/dora
    - name: Lint with flake8 dora quicksight
      run: |
        flake8 --config=./.config/.flake8 ./services/ingestion/dora
    - name: Lint with yamllint dora ignestion
      run: |
        yamllint -c ./.config/.yamllint ./services/ingestion/dora

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/ingestion/dora
    container:
      image: lambci/lambda:build-python3.7

    steps:
    - uses: actions/checkout@v2
    - name: Test with tox
      working-directory: './services/ingestion/dora'
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        tox