
name: Dataplattform - package - common

on: 
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    paths:
      - 'packages/common/**'
      - '.config/.flake8'
      - '.config/.yamllint'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'packages/common/**'
      - '.config/.flake8'
      - '.config/.yamllint'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config=./.config/.flake8 ./packages/common
    - name: Lint with yamllint
      run: |
        pip install yamllint
        yamllint -c ./.config/.yamllint ./packages/common
  
  test:
    runs-on: ubuntu-latest
    container:
      image: lambci/lambda:build-python3.7
      
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: './packages/common'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      working-directory: './packages/common'
      run: |
        pip install pytest ../testing
        pytest 