name: Run Python tests

on:
  push:
    branches:
      - feature/main-cicd
  pull_request:
    branches:
      - main
    paths:
      - 'services/**'
      - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: lambci/lambda:build-python3.7
    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/main-cicd
          fetch-depth: 0

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Look for Tox folders affected by change
        id: get_changed_tox
        env:
          CHANGED_FILES: ${{ steps.changed_files.outputs.all }}
        run: |
          source .workflow-scripts/test-python/get_tox_changes.sh
          look_for_changed_tox_directories

      - name: Set up Python 3.7
        if: ${{ steps.get_changed_tox.outputs.should_test == 'true' }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Tox
        if: ${{ steps.get_changed_tox.outputs.should_test == 'true' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Run Tox
        if: ${{ steps.get_changed_tox.outputs.should_test == 'true' }}
        run: |
          source .workflow-scripts/test-python/run_tox.sh
          run_tox "$TOX_DIRS"
